# Generated by Django 6.0 on 2025-12-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalavraBloqueada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=100, unique=True, verbose_name='Palavra/Termo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Palavra Bloqueada',
                'verbose_name_plural': 'Palavras Bloqueadas',
                'ordering': ['palavra'],
            },
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
    ]
