# Generated by Django 5.1.6 on 2025-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_remove_categoria_receita_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('categoria', models.ManyToManyField(related_name='receitas', to='categorias.categoria')),
            ],
        ),
    ]
