# Generated by Django 5.1.6

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0002_remove_categoria_receita_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
                ('visualizacoes', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='receitas/capas/', verbose_name='Imagem de Capa')),
                ('categoria', models.ManyToManyField(related_name='receitas_categoria', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
        migrations.CreateModel(
            name='ModoPreparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ordem', models.IntegerField(verbose_name='Número do Passo')),
                ('descricao', models.TextField(verbose_name='Descrição do Passo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos', to='receitas.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Modo de Preparo',
                'ordering': ['num_ordem'],
                'unique_together': {('receita', 'num_ordem')},
            },
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=50, verbose_name='Quantidade')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.ingrediente')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'verbose_name': 'Ingrediente da Receita',
                'verbose_name_plural': 'Ingredientes da Receita',
                'unique_together': {('receita', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(related_name='receitas_usando', through='receitas.ReceitaIngrediente', to='receitas.ingrediente'),
        ),
    ]
