# Generated by Django 5.1.6 on 2025-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='referencia',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Referência'),
        ),
    ]
