# Generated by Django 5.1.6 on 2025-11-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='descricao',
            field=models.TextField(default='Descrição Padrão'),
            preserve_default=False,
        ),
    ]
