# Generated by Django 5.1.6 on 2025-11-20 00:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ingrediente',
                'verbose_name_plural': 'Ingredientes',
            },
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.RemoveField(
            model_name='receita',
            name='modo_preparo',
        ),
        migrations.AddField(
            model_name='receita',
            name='data_publicacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 20, 0, 55, 23, 36438, tzinfo=datetime.timezone.utc), verbose_name='Data de Publicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receita',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='receitas/capas/', verbose_name='Imagem de Capa'),
        ),
        migrations.AddField(
            model_name='receita',
            name='visualizacoes',
            field=models.IntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.RemoveField(
            model_name='receita',
            name='ingredientes',
        ),
        migrations.CreateModel(
            name='ReceitaIngrediente',
            fields=[
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='receitas.receita')),
                ('quantidade', models.CharField(max_length=50, verbose_name='Quantidade')),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de Medida')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.ingrediente')),
            ],
            options={
                'verbose_name': 'Ingrediente da Receita',
                'verbose_name_plural': 'Ingredientes da Receita',
                'unique_together': {('receita', 'ingrediente')},
            },
        ),
        migrations.AddField(
            model_name='receita',
            name='ingredientes',
            field=models.ManyToManyField(related_name='receitas_usando', through='receitas.ReceitaIngrediente', to='receitas.ingrediente'),
        ),
        migrations.CreateModel(
            name='ModoPreparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ordem', models.IntegerField(verbose_name='Número do Passo')),
                ('descricao', models.TextField(verbose_name='Descrição do Passo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos', to='receitas.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Modo de Preparo',
                'ordering': ['num_ordem'],
                'unique_together': {('receita', 'num_ordem')},
            },
        ),
    ]
