# Generated by Django 5.1.6 on 2025-12-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='curtidas',
            field=models.IntegerField(default=0, verbose_name='Curtidas'),
        ),
    ]
