# Generated by Django 5.1.6 on 2025-11-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_remove_categoria_receitas_vinculadas_and_more'),
        ('receitas', '0003_ingrediente_alter_receita_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.ManyToManyField(related_name='receitas_categoria', to='categorias.categoria'),
        ),
    ]