# Generated by Django for restrição alimentar fields
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_curtidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='sem_lactose',
            field=models.BooleanField(default=False, verbose_name='Sem Lactose'),
        ),
        migrations.AddField(
            model_name='receita',
            name='sem_gluten',
            field=models.BooleanField(default=False, verbose_name='Sem Glúten'),
        ),
        migrations.AddField(
            model_name='receita',
            name='vegano',
            field=models.BooleanField(default=False, verbose_name='Vegano'),
        ),
        migrations.AddField(
            model_name='receita',
            name='vegetariano',
            field=models.BooleanField(default=False, verbose_name='Vegetariano'),
        ),
    ]
