# Generated by Django 5.1.6 on 2025-11-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(default='Cozinha Inclusiva', max_length=255, verbose_name='Título Principal do Site')),
                ('descricao_meta', models.CharField(max_length=500, verbose_name='Descrição para Motores de Busca (SEO)')),
                ('email_contato', models.EmailField(max_length=254, verbose_name='E-mail de Contato Principal')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone (WhatsApp)')),
                ('link_instagram', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link para Instagram')),
                ('link_facebook', models.URLField(blank=True, max_length=255, null=True, verbose_name='Link para Facebook')),
                ('logo_header', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo do Cabeçalho')),
            ],
            options={
                'verbose_name': 'Configuração do Website',
                'verbose_name_plural': 'Configurações do Website',
            },
        ),
    ]
