# Generated by Django 5.1.6 on 2025-11-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='receita_popular',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
