# Generated by Django 5.1.6 on 2025-11-20 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_remove_categoria_receita_popular_and_more'),
        ('receitas', '0003_ingrediente_alter_receita_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='receitas_vinculadas',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='visualizacoes',
        ),
        migrations.AddField(
            model_name='categoria',
            name='receita_mais_popular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categoria_mais_popular_vinculada', to='receitas.receita', verbose_name='Receita Mais Popular'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.CreateModel(
            name='CategoriaReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.categoria')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.receita')),
            ],
            options={
                'verbose_name': 'Vínculo Categoria-Receita',
                'verbose_name_plural': 'Vínculos Categoria-Receita',
                'unique_together': {('categoria', 'receita')},
            },
        ),
        migrations.AddField(
            model_name='categoria',
            name='receitas',
            field=models.ManyToManyField(related_name='categorias_vinculadas', through='categorias.CategoriaReceita', to='receitas.receita'),
        ),
    ]
